/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fblacode;
import java.util.Random;
import java.util.Scanner;
import java.util.ArrayList;
import Student.Student;
import java.util.*;
import java.io.*;


/**
 *
 * @author amank
 */
public class bookredemption extends javax.swing.JFrame {

    /**
     * Creates new form bookredemption
     */
    public bookredemption() {
        initComponents(); //initializing method
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        Displaystudent = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        name = new javax.swing.JTextField();
        javax.swing.JButton addwithbook = new javax.swing.JButton();
        Addstudentnobook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gradepicker = new javax.swing.JComboBox<>();
        displaylist = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        bookiddisplay = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        assigncode = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Help = new javax.swing.JButton();
        ViewStudent = new javax.swing.JButton();
        Label = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        Displaystudent.setText("View Students");
        Displaystudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaystudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        addwithbook.setText("Add Student/Assign Book");
        addwithbook.setToolTipText("add student with an ID");
        addwithbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addwithbookActionPerformed(evt);
            }
        });

        Addstudentnobook.setText("Add Student/No Book");
        Addstudentnobook.setToolTipText("Add a student without a book ID");
        Addstudentnobook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstudentnobookActionPerformed(evt);
            }
        });

        jLabel1.setText("NAME");
        jLabel1.setToolTipText("Name of student");

        jLabel2.setText("GRADE");
        jLabel2.setToolTipText("Grade student is currently in");

        gradepicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12" }));
        gradepicker.setName("gradepicker"); // NOI18N
        gradepicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradepickerActionPerformed(evt);
            }
        });

        displaylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        displaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaylistActionPerformed(evt);
            }
        });

        jLabel3.setText("Book Id");
        jLabel3.setToolTipText("");

        bookiddisplay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        save.setText("Save");
        save.setToolTipText("Saves inforrmation that is inported");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        assigncode.setText("Assign New Code");
        assigncode.setToolTipText("Used to assign a new code for students without a book or new added students");
        assigncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigncodeActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(assigncode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(assigncode)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(assigncode)
                .addGap(30, 30, 30))
        );

        jLabel4.setText("Student Name");
        jLabel4.setToolTipText("Name of students imported and saved");

        Help.setText("Help ?");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        ViewStudent.setText("View Students");
        ViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentActionPerformed(evt);
            }
        });

        Label.setText("Issuance of E-books");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Help)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewStudent)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(name)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addwithbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookiddisplay)
                                    .addComponent(jLabel3))
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Addstudentnobook, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gradepicker, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(gradepicker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addwithbook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addstudentnobook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookiddisplay)
                        .addGap(9, 9, 9)
                        .addComponent(displaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewStudent))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(Help))
                .addGap(55, 55, 55))
        );

        gradepicker.getAccessibleContext().setAccessibleName("");
        Help.getAccessibleContext().setAccessibleDescription("Redirects user to Help Page");
        ViewStudent.getAccessibleContext().setAccessibleDescription("Click button to accses students' names");
        Label.getAccessibleContext().setAccessibleName("Label");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        //method for name 
    }//GEN-LAST:event_nameActionPerformed

    private void AddstudentnobookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstudentnobookActionPerformed
        // TODO add your handling code here:
        // method to adding a student without a book
        String sname = name.getText();
        int grade= gradepicker.getSelectedIndex();
        myclass.add(new Student(sname.substring(0,sname.indexOf(" ")),sname.substring(sname.indexOf(" ")+1),grade));
        displaylist.addItem(myclass.get(myclass.size()-1).getName());
        name.setText("");

    }//GEN-LAST:event_AddstudentnobookActionPerformed

    private void gradepickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradepickerActionPerformed
        // TODO add your handling code here:
        // method for user to pick grade
    }//GEN-LAST:event_gradepickerActionPerformed

    private void addwithbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addwithbookActionPerformed
        // TODO add your handling code here:
        // method to add a student with a book
        String sname = name.getText();
        int grade= gradepicker.getSelectedIndex();
        if (grade==0)grade = 9;else if (grade==1)grade =10;else if(grade==2)grade=11;else grade=12;
        myclass.add(new Student(sname.substring(0,sname.indexOf(" ")),sname.substring(sname.indexOf(" ")+1),grade,bookid));
        bookid++;
        displaylist.addItem(myclass.get(myclass.size()-1).getName());
        name.setText("");
    }//GEN-LAST:event_addwithbookActionPerformed

    private void DisplaystudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaystudentActionPerformed
        // TODO add your handling code here:
        //method to have a drop down list to display students name
        displaylist.removeAll();
        
       for(int i = 0;i<myclass.size();i++){
        displaylist.addItem(myclass.get(i).getName());
       }

    }//GEN-LAST:event_DisplaystudentActionPerformed

    private void displaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaylistActionPerformed
        // TODO add your handling code here:
        //bookiddisplay.setText(myclass.get(displaylist.getSelectedIndex()).getEbookcode()+"");
        bookiddisplay.setText(String.valueOf(myclass.get(displaylist.getSelectedIndex()-1).getEbookcode()));
 
    }//GEN-LAST:event_displaylistActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        // method that saves all information to the data text file
              try{
            
            PrintWriter printer=new PrintWriter(new File("data.txt"));
            printer.flush();
            printer.println(bookid);
               for (int i =0;i<myclass.size();i++)     
               {
                   System.out.println(myclass.get(i).toString());

               printer.println(myclass.get(i).toString());
             // printdisplay.setText(printdisplay.getText()+"\n"+myclass.get(myclass.size()-1).toString());

            }
               printer.close();
        }catch(FileNotFoundException e){System.out.println("no file");}
    }//GEN-LAST:event_saveActionPerformed

    private void assigncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigncodeActionPerformed
        // Code will check current id setting and assign a ebook id if the current id is set to 0
        // method to assign code to students
        if(bookiddisplay.getText().equals("0"))
        {
        myclass.get(displaylist.getSelectedIndex()-1).setEbookcode(bookid);
        bookiddisplay.setText(bookid+" ");
        bookid++;
        }
       
       //assigncode
    }//GEN-LAST:event_assigncodeActionPerformed

    private void ViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentActionPerformed
        // Places current students in the displaylist component
        // Method to view students
        displaylist.removeAll();
        
       for(int i = 0;i<myclass.size();i++){
        displaylist.addItem(myclass.get(i).getName());
        
       }
    }//GEN-LAST:event_ViewStudentActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookredemption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookredemption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookredemption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookredemption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String fname,lname;
        int grade,gb;
        try{
            Scanner scan=new Scanner(new File("data.txt"));
            if(scan.hasNext())
            bookid=scan.nextInt();
            
           while (scan.hasNext())
            {
              fname=scan.next();
              lname=scan.next();
              grade=scan.nextInt();
              gb=scan.nextInt();
              myclass.add(new Student(fname,lname,grade,gb));
              
             // printdisplay.setText(printdisplay.getText()+"\n"+myclass.get(myclass.size()-1).toString());

            }
         
           scan.close();
            
        }catch(FileNotFoundException e){System.out.println("no file");}
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookredemption().setVisible(true);
            }
        });
        
    }
    private static ArrayList<Student> myclass= new ArrayList<>();
    private static int bookid=100;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addstudentnobook;
    private javax.swing.JButton Displaystudent;
    private javax.swing.JButton Help;
    private javax.swing.JLabel Label;
    private javax.swing.JButton ViewStudent;
    private javax.swing.JButton assigncode;
    private javax.swing.JLabel bookiddisplay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> displaylist;
    private javax.swing.JComboBox<String> gradepicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
